### ISSUE TITLE
USER STORY: Miscellaneous Tasks

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/nsc-events-android#188]
As a developer, I would like to:

- [x] [On Login page: update Toast message "Welcome null to NSC Events!" to display user's name instead of null](https://github.com/SeattleColleges/nsc-events-android/issues/190) 
[Updating backend to accommodate this](https://github.com/SeattleColleges/nsc-events-nestjs/issues/72) 
- [x] [On Home page: remove "eventTitle" from titles of event cards](https://github.com/SeattleColleges/nsc-events-android/issues/189)
- [x] [On Edit Detail page: remove "event" from the names of the fields in event detail card (eventTitle should be Title)](https://github.com/SeattleColleges/nsc-events-android/issues/189)
