### ISSUE TITLE
USER STORY: Nav Bar

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/nsc-events-android#200]
As a developer, I'd like to create a drop down with the below features:

- [x] [Hamburger button should open drop down menu](https://github.com/SeattleColleges/nsc-events-android/issues/201)
- [x] [Add sign up link to menu](https://github.com/SeattleColleges/nsc-events-android/issues/201)
- [x] [Add log in link to menu](https://github.com/SeattleColleges/nsc-events-android/issues/201)
- [x] Remove the login button and edit button next to the hamburger menu button
