### ISSUE TITLE
USER STORY: Event Detail Page

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/nsc-events-android#216]
As a developer, I will want to:

- [x] [Remove "Title" and "Description" in front of title and description](https://github.com/SeattleColleges/nsc-events-android/issues/217)
- [x] [Make event image larger](https://github.com/SeattleColleges/nsc-events-android/issues/217)
- [x] [Edit, delete, and archive buttons should only be accessible to admins and creators](https://github.com/SeattleColleges/nsc-events-android/issues/218)
