### ISSUE TITLE
USER STORY: Creator View Page

### ISSUE THREAD

**Issue by Robel-003** [SeattleColleges/nsc-events-android#96]
**Task**: As a creator I want a page giving me the ability to create and view events  

**Solution**: Create a page specifically for the creator giving them the ability to create event(s), view their events, and view all events

<img width="139" alt="Screenshot 2023-10-30 at 4 05 42 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/116779961/bb8d1480-d9ae-427c-ae45-eb1f434c16fb">

**_Specific Issues_**:

- [ ] Create a _Create Event_ button, routing creator’s to the create event page allowing them to create events

- [ ] Create a _View My Events_ button, routing creator’s to the landing page where they can view their own created events (landing page events filtered so creator’s can view their own events) 

- [ ] Create a _View All Events_ button, routing them to the landing page where creator’s can view all events

**Comment by taylorpapke** [comment]
@Ali-7s Make sure to create issues for your PR's. There is still an issue that you need to make for PR https://github.com/SeattleColleges/nsc-events-android/pull/111

Also make sure that you are checking off the requirements above for each issue that you create for this user story.
