### ISSUE TITLE
USER STORY: edit/delete buttons functionality  

### ISSUE THREAD

**Issue by Robel-003** [SeattleColleges/nsc-events-android#97]
**Task**: As a creator of an event or an admin, I want the ability to edit/delete events and increment number of attendees for an event

**Solution**: add functionality to these buttons → _edit, delete, attend_ (buttons’ functionality will later be visible only for creator of event(s) or admin)

<img width="277" alt="Screenshot 2023-10-30 at 4 12 42 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/116779961/19291a1e-ea6b-4d8a-aaf5-a5cc5c6a7884">

**_Specific issues_**:	

- [ ] When _edit_ button is clicked, they should be taken a separate page giving them permission to edit all fields. Leverage the create event page to be used as an editable page for editing/updating events 

- [ ] When _delete_ button is clicked, a pop up should appear asking them of their sure they want to delete this event

- [ ] The _attend_ button will keep count, incrementing the number of people attending event. A toast message can be displayed successfully showing the increment of an attendee and showing a total count of attendees

**Comment by taylorpapke** [comment]
Edited the title of this to differentiate from user story #54 as they were similarly named but dealing with different aspects of of the features. This story focuses on giving the edit, delete and attend buttons UI functionality at the press of a button while #54 deals with only the delete button and what occurs in the backend when it is pressed.
